### ISSUE TITLE
Uncaught Error: Not Found

### ISSUE THREAD

**Issue by ernestbofill** [BenSower/npm-license-checker#1]
[Enter steps to reproduce:]

1. ...
Toggle npm-lisence-checker in package.json
2. ...
It begins to print licenses but then it crashed

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [npm-license-checker](https://github.com/BenSower/npm-license-checker) package 1.1.2

### Stack Trace

Uncaught Error: Not Found

```
At C:\Users\eby\.atom\packages\npm-license-checker\lib\npm-license-checker.coffee:74

Error: Not Found
    at Request.callback (/packages/npm-license-checker/node_modules/superagent/lib/node/index.js:795:17)
    at /packages/npm-license-checker/node_modules/superagent/lib/node/index.js:997:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:23.6.0 npm-license-checker:toggle (div.line)
```

### Non-Core Packages

```
npm-license-checker 1.1.2 
```

**Comment by BenSower** [comment]
Thanks for submitting the bug, I'll have a look at it, when I am back from
my holiday!
